name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v7.0.1

      - uses: pnpm/setup@v3.0.0
        with:
          cache: true

      - name: Build
        shell: "bash"
        run: pnpm build
