name: E2E Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    paths:
      - "public/**"
      - "src/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install
        shell: "bash"
        run: pnpm i

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Build application for tests
        run: pnpm build --site http://localhost:4321/

      - name: Run e2e tests
        run: pnpm test:e2e

      - uses: actions/upload-artifact@v5
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
